#!/bin/sh

# Set these paths appropriately

BIN=/Users/aldofpr/Desktop/PAN/AuthorIdentification/src/pos_tagger/bin
CMD=/Users/aldofpr/Desktop/PAN/AuthorIdentification/src/pos_tagger/cmd
LIB=/Users/aldofpr/Desktop/PAN/AuthorIdentification/src/pos_tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
