#!/bin/sh

# Set these paths appropriately

BIN=/Users/aldofpr/Desktop/PAN/AuthorIdentification/src/pos_tagger/bin
CMD=/Users/aldofpr/Desktop/PAN/AuthorIdentification/src/pos_tagger/cmd
LIB=/Users/aldofpr/Desktop/PAN/AuthorIdentification/src/pos_tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
